spring.application.name=Backend

# Puerto
server.port=${PORT:8080}

# H2
spring.datasource.url=jdbc:h2:file:./data/energiadb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Configuracion del servicio de Data Science (FastAPI)
ml.service.url=${ML_SERVICE_URL}

# Configuracion del bot de Telegram
telegram.bot.username=EnergiAI_27_bot
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

# Bypass Railway cache and force override
spring.main.allow-bean-definition-overriding=true
